// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card.vue')['default']
    Counter: typeof import('./modules/my-module/components/Counter.vue')['default']
    Icon: typeof import('@iconify/vue')['Icon']
    MyModule: typeof import('./modules/my-module/index.vue')['default']
    MyOtherModule: typeof import('./modules/my-other-module/index.vue')['default']
    ReloadPrompt: typeof import('./components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TechList: typeof import('./modules/my-module/components/TechList.vue')['default']
  }
}

export {}
